services:
    _defaults:
        autowire: true

    YsGroups\:
        resource: '../src/*'
        exclude: '../src/{constants.php}'

    YsGroups\Controller\Admin\Admin:
        public: true

    YsGroups\Controller\Front\Front:
        public: true

    YsGroups\Services\RewriteRules:
        public: true

    YsGroups\Services\Session:
        public: true

    YsGroups\Services\NotLoggedInRedirections:
        public: true

    YsGroups\Services\Mailer:
        public: true